spring.application.name=RecruitIQ
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recruitiq}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ghuy$178}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET:recruitiq_jwt_secret_key_must_be_at_least_256_bits_long_for_security}
jwt.expiration-ms=${JWT_EXPIRATION_MS:28800000}

# LLM API
llm.api.key=${LLM_API_KEY:AIzaSyDCg6tHGEaqQx0bCIM33PnOEnK5VrzhmZ8}
llm.api.url=https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent
llm.api.model=${LLM_API_MODEL:gemini-2.5-flash}

# File Upload
upload.dir=${UPLOAD_DIR:./uploads}
app.public-base-url=${APP_PUBLIC_BASE_URL:http://localhost:8080}
app.upload-base-path=${APP_UPLOAD_BASE_PATH:/uploads}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

# Thymeleaf
spring.thymeleaf.cache=false

# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

# Mail Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:programmize178@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:czbz lsux olbo yirw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dufnaw96e}
cloudinary.api-key=${CLOUDINARY_API_KEY:371681245413421}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:ru3DXhJQsoUdVS5klYX5Wi9hkqs}

# Frontend URL
recruitiq.frontend.base-url=${RECRUITIQ_FRONTEND_BASE_URL:http://localhost:5173}

